// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://qgrwslhmamroajbeuyfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFncndzbGhtYW1yb2FqYmV1eWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDczNzAsImV4cCI6MjA3MzUyMzM3MH0.jlb8CqhBkYLBoeCe-CHmnBqdPS4PIKySVaHvMEpl5ZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);